### ISSUE TITLE
Remove events > database and commands > database from *.yaml file

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_common#133]
The *.yaml command/event database parameters must be deleted.
EventHandler will use Postgresql databese defined in events/commands > queue.

```yaml
database:
        path: ./tests/local_db.lmdb
        name: database_events_test
```
