### ISSUE TITLE
Add items and queue to Saga MinosConfig

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_common#188]
```yaml
saga:
    items:
        - name: AddOrder
          controller: tests.services.SagaTestService.SagaService
          action: add_order
        - name: DeleteOrder
          controller: tests.services.SagaTestService.SagaService
          action: delete_order
    queue:
        database: order_db
        user: minos
        password: min0s
        host: localhost
        port: 5432
        records: 10
        retry: 2
```
