### ISSUE TITLE
Add Discovery Service Configuration

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_common#341]
The microservice must know where the Discovery Service is located in order to make subscribe/unsubscribe requests.

It is proposed to add the following structure in config.yml:
```yaml
....
discovery:
    host: discovery-service
    port: 8080
    subscribe:
        path: subscribe
        method: POST
    unsubscribe:
        path: unsubscribe?name=
        method: POST
    discover:
        path: discover?name=
        method: GET
```

**Comment by albamig** [comment]
That's nice @vladyslav-fenchak! I would just an `endpoint` level, so it's consistent with other config files in Minos.

```yaml
....
discovery:
    host: discovery-service
    port: 8080
    endpoints:
        subscribe:
            path: subscribe
            method: POST
        unsubscribe:
            path: unsubscribe?name=
            method: POST
        discover:
            path: discover?name=
            method: GET
```
