### ISSUE TITLE
MinosConfig must have the connection data to the broker queue database.

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_common#37]
The broker has a queue that is stored in the PostgreSQL database. For this it is necessary to include this configuration in the "events" and "commands". Also in case there are 2 different databases in the future.

This is the original YAML:
``` yaml
service:
    name: Order
rest:
    host: localhost
    port: 8900
    endpoints:
        - name: AddOrder
          route: /order
          method: POST
          controller: minos.services.OrderService
          action: add_order
events:
    broker: localhost
    port: 9092
    database:
        path: ./tests/local_db.lmdb
        name: database_events_test
    items:
        - name: TicketAdded
          controller: minos.services.CQRSService
          action: ticket_added
        - name: TicketDeleted
          controller: minos.services.CQRSService
          action: ticket_deleted
        - name: OrderAdded
          controller: minos.services.CQRSService
          action: order_added
commands:
    broker: localhost
    port: 9092
    database:
        path: ./tests/local_db.lmdb
        name: database_commands_test
    items:
        - name: AddOrder
          controller: minos.services.OrderService
          action: add_order
        - name: DeleteOrder
          controller: minos.services.OrderService
          action: delete_order
        - name: UpdateOrder
          controller: minos.services.OrderService
          action: update_order
        - name: GetOrder
          controller: minos.service.OrderService
          action: get_order
```

This is what would be added in events/commands:
``` yaml
events:
    ...
    queue:
        database: broker_db
        user: broker
        password: *****
        host: localhost
        port: 5432
commands:
    ...
    queue:
        database: broker_db
        user: broker
        password: *****
        host: localhost
        port: 5432
```

**In the end it would look like this:**
``` yaml
service:
    name: Order
rest:
    host: localhost
    port: 8900
    endpoints:
        - name: AddOrder
          route: /order
          method: POST
          controller: minos.services.OrderService
          action: add_order
events:
    broker: localhost
    port: 9092
    database:
        path: ./tests/local_db.lmdb
        name: database_events_test
    items:
        - name: TicketAdded
          controller: minos.services.CQRSService
          action: ticket_added
        - name: TicketDeleted
          controller: minos.services.CQRSService
          action: ticket_deleted
        - name: OrderAdded
          controller: minos.services.CQRSService
          action: order_added
    queue:
        database: broker_db
        user: broker
        password: *****
        host: localhost
        port: 5432
commands:
    broker: localhost
    port: 9092
    database:
        path: ./tests/local_db.lmdb
        name: database_commands_test
    items:
        - name: AddOrder
          controller: minos.services.OrderService
          action: add_order
        - name: DeleteOrder
          controller: minos.services.OrderService
          action: delete_order
        - name: UpdateOrder
          controller: minos.services.OrderService
          action: update_order
        - name: GetOrder
          controller: minos.service.OrderService
          action: get_order
    queue:
        database: broker_db
        user: broker
        password: *****
        host: localhost
        port: 5432
```
