### ISSUE TITLE
Refactor configuration file

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_common#422]
Tasks:
* [x] https://github.com/Clariteia/minos_microservice_common/issues/437
* [x] https://github.com/Clariteia/minos_microservice_common/issues/444
* [x] https://github.com/Clariteia/minos_microservice_common/issues/450
* [ ] https://github.com/Clariteia/minos_microservice_common/issues/440
* [x] https://github.com/Clariteia/minos_microservice_common/issues/453

Here is a proposal of the new config file: 

```yaml
name: tickets
injections:
  command_broker: minos.networks.CommandBroker
  command_reply_broker: minos.networks.CommandReplyBroker
  event_broker: minos.networks.EventBroker
  repository: minos.common.PostgreSqlRepository
  saga_manager: minos.saga.SagaManager
  snapshot: minos.common.PostgreSqlSnapshot
  discovery: minos.networks.DiscoveryConnector
services:
  - minos.networks.CommandConsumerService
  - minos.networks.CommandHandlerService
  - minos.networks.CommandReplyConsumerService
  - minos.networks.CommandReplyHandlerService
  - minos.networks.EventConsumerService
  - minos.networks.EventHandlerService
  - minos.networks.RestService
  - minos.networks.SnapshotService
  - minos.networks.ProducerService
interfaces:
  rest:
    engine: aiohttp
    host: 0.0.0.0
    port: 8085
  broker:
    engine: kafka
    broker: localhost
    port: 9092
    queue:
      database: ticket_db
      user: minos
      password: min0s
      host: localhost
      port: 5432
      records: 10
      retry: 2
commands:
    service: src.OrderCommandService
events:
    service: src.OrderQueryService
queries:
    service: src.OrderQueryService
aggregate:
  repository:
    engine: postgres
    database: ticket_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
  snapshot:
    engine: postgres
    database: ticket_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
saga:
  storage:
    path: "./ticket.lmdb"
discovery:
  host: localhost
  port: 5567
```

┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/15xp91v) by [Unito](https://www.unito.io)
