### ISSUE TITLE
Define the `service` for `commands`, `queries` and `events` on the config file.

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_common#437]
in addition to the current config file contents, it's needed to include the `service` field.

Here is an example:
```
commands:
    service: src.OrderCommandService
events:
    service: src.OrderQueryService
queries:
    service: src.OrderQueryService
```

┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/17nuhen) by [Unito](https://www.unito.io)
