### ISSUE TITLE
Create common `broker` entry on `minos.common.MinosConfig`

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_common#453]
Here is an example of the current config file:
```yaml
events:
  broker: localhost
  port: 9092
  queue:
    database: order_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
  service: src.OrderQueryService
queries:
  service: src.OrderQueryService
commands:
  broker: localhost
  port: 9092
  service: src.OrderCommandService
  queue:
    database: order_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
saga:
  broker: localhost
  port: 9092
  storage:
    path: "./order.lmdb"
  items:
    - name: CreateOrder
      controller: src
      action: CREATE_ORDER
  queue:
    database: order_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
``` 

The new proposed solution is:
```yaml
broker: 
  host: localhost
  port: 9092
  queue:
    database: order_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
events:
  service: src.OrderQueryService
queries:
  service: src.OrderQueryService
commands:
  service: src.OrderCommandService
saga:
  storage:
  path: "./order.lmdb"
  items:
    - name: CreateOrder
      controller: src
      action: CREATE_ORDER
    retry: 2
 ```

┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/18by5t0) by [Unito](https://www.unito.io)
