### ISSUE TITLE
MinosConfig queue parameter must support the attribute "retry"

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_common#51]
The configuration define the number of the retry that the broker must respect for event/command network

this parameter is valid for **events** and **commands** attributes
```yaml

events:
    ...
    queue:
        ...
        retry: 2

commands:
     ....
     queue:
         ....
         retry: 2

``` 

the parameter is an integer
