### ISSUE TITLE
Create `interfaces` section in `MinosConfig` file

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_common#594]
Currently `rest` and `broker` entries in the configuration file are independent. This issue is intended to create a parent section that groups them.

Here is an example before and after the refactor:
* Before:
```yaml
service:
    ...
rest:
    host: 0.0.0.0
    port: 8000
broker:
    host: kafka
    port: 9092
    queue:
        ...
...
```
* After:
```yaml
service:
    ...
interfaces:
    rest:
        host: 0.0.0.0
        port: 8000
    broker:
        host: kafka
        port: 9092
        queue:
            ...
...
```
